runtime: go120

handlers:
- url: /
  mime_type: text/plain
  static_files: static/index.html
  upload: static/index.html
  http_headers:
    Strict-Transport-Security: max-age=31536000; includeSubDomains
- url: /.*
  script: _go_app
