runtime: go120

handlers:
- url: /
  mime_type: text/plain
  static_files: static/index.html
  upload: static/index.html
- url: /(.*\.(gif|png|jpg))$
  static_files: static/\1
  upload: static/.*\.(gif|png|jpg)$
- url: /.*
  script: _go_app
